# Generated by Django 5.0.6 on 2024-06-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AddField(
            model_name='vendedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil/'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='idade_vendedor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
