# Generated by Django 5.0.6 on 2024-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja1', '0002_alter_vendedor_options_vendedor_foto_vendedor_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='idade_vendedor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
