# Generated by Django 5.0.6 on 2024-06-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_do_produto',
            field=models.ImageField(default=None, upload_to='imagens/', null=True),
            preserve_default=False,
        ),
    ]
