# Generated by Django 5.0.6 on 2024-06-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_imagem_do_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='maior_de_idade',
            field=models.CharField(blank=True, choices=[('Maior', 'pode beber'), ('Menor', 'não pode beber')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_do_produto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
