# Generated by Django 5.0.6 on 2024-06-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_maior_de_idade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('pk',), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
