# Generated by Django 5.0.6 on 2024-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='foto_perfil/')),
                ('escolaridade', models.CharField(max_length=30)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ano_inicio', models.DateField()),
                ('ano_conclusao', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2)),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
            },
        ),
    ]
