# Generated by Django 5.0.6 on 2024-07-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.CharField(max_length=100)),
                ('idade_aluno', models.PositiveIntegerField()),
                ('quant_notas', models.PositiveIntegerField()),
            ],
        ),
    ]
