# Generated by Django 5.0.6 on 2024-06-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='foto_perfil/')),
                ('ano_nascimento', models.PositiveIntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não binario')], max_length=4)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ('pk',),
            },
        ),
    ]
