# Generated by Django 5.0.6 on 2024-07-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade_jogador', models.PositiveIntegerField()),
                ('data_nasc', models.DateField()),
                ('foto_perfil', models.ImageField(upload_to='perfil/')),
                ('documentos', models.FileField(upload_to='documentos/')),
                ('posicao', models.PositiveIntegerField()),
                ('time_atual', models.CharField(max_length=50)),
            ],
        ),
    ]
