# Generated by Django 5.0.6 on 2024-07-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='foto_perfil',
            field=models.ImageField(upload_to='fot_perfil/'),
        ),
    ]
