# Generated by Django 5.0.6 on 2024-06-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('especializacao', models.CharField(max_length=50)),
                ('crm', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'Doutor',
                'verbose_name_plural': 'Doutores',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data_nacimento', models.DateField()),
                ('diagnostico', models.TextField()),
            ],
        ),
    ]
