# Generated by Django 5.0.6 on 2024-05-21 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Formas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricacao', models.TextField()),
                ('data_insercao', models.DateTimeField()),
                ('quimico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuvem.pessoa')),
            ],
        ),
    ]
