# Generated by Django 5.0.6 on 2024-05-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.PositiveIntegerField()),
            ],
        ),
    ]
