# Generated by Django 5.0.6 on 2024-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=20)),
                ('valor_marca', models.DecimalField(decimal_places=2, max_digits=6)),
                ('modelo', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='foto_perfil/')),
            ],
        ),
    ]
