# Generated by Django 5.0.6 on 2024-05-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data_fabricacao', models.DateField()),
                ('descricacao', models.TextField()),
                ('criador', models.CharField(max_length=20)),
            ],
        ),
    ]
