# Generated by Django 5.0.7 on 2024-07-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcursoUEMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capa_concurso', models.ImageField(upload_to='fotos_capa')),
                ('doc_edital', models.FileField(upload_to='edital_docs')),
            ],
        ),
    ]
