# Generated by Django 5.0.6 on 2024-05-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Preço Produto',
                'verbose_name_plural': 'Preços Produtos',
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
