# Generated by Django 5.0.6 on 2024-05-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mks', '0002_precoprodutos_usuario_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='precoprodutos',
            name='ano_fabricacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precoprodutos',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='precoprodutos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
