# Generated by Django 5.0.6 on 2024-05-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.PositiveIntegerField()),
                ('rg', models.PositiveIntegerField()),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('data_inclusao', models.DateField()),
            ],
        ),
    ]
