# Generated by Django 5.0.7 on 2024-07-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=150)),
                ('rg_ie', models.CharField(max_length=150)),
                ('zip_code', models.TextField(max_length=11)),
                ('andress', models.TextField(max_length=150)),
                ('neighborhood', models.TextField(max_length=150)),
                ('number', models.TextField(max_length=5)),
                ('cite', models.TextField(max_length=30)),
                ('state', models.TextField(max_length=3)),
                ('ddd', models.TextField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
