# Generated by Django 5.0.7 on 2024-07-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='andress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='cite',
            new_name='city',
        ),
    ]
