# Generated by Django 5.0.6 on 2024-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preco')),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('manual', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
