# Generated by Django 5.0.6 on 2024-06-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('emai', models.EmailField(max_length=254, verbose_name='email')),
                ('foto', models.ImageField(upload_to='foto_perfil/')),
            ],
        ),
    ]
