# Generated by Django 5.0.6 on 2024-05-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('tamanho', models.IntegerField()),
                ('tipo', models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript')], max_length=2)),
            ],
        ),
    ]
