# Generated by Django 5.0.6 on 2024-05-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('R', 'Ramon'), ('G', 'Glêssio')], max_length=2)),
            ],
        ),
    ]
