# Generated by Django 5.0.6 on 2024-05-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JS', '0002_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(choices=[('Ramon', 'Ramon'), ('G', 'Glêssio')], max_length=10),
        ),
    ]
