# Generated by Django 5.0.6 on 2024-05-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JS', '0003_alter_professor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoMercadorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
            ],
        ),
        migrations.AlterField(
            model_name='var',
            name='tipo',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript')], max_length=10),
        ),
    ]
