# Generated by Django 5.0.6 on 2024-05-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JS', '0004_precomercadorias_alter_var_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='nome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='var',
            name='tipo',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript')], max_length=20),
        ),
    ]
