# Generated by Django 5.0.6 on 2024-05-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JS', '0005_alter_var_nome_alter_var_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='precomercadorias',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
