# Generated by Django 5.0.6 on 2024-05-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('quant_paginas', models.IntegerField()),
                ('tipo', models.CharField(choices=[('DE', 'De Estudo'), ('C', 'Cotidiano')], max_length=2)),
            ],
        ),
    ]
