# Generated by Django 5.0.6 on 2024-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='biblia',
            name='tipo',
            field=models.CharField(choices=[('DE', 'De Estudo'), ('C', 'Cotidiano'), ('P', 'Pesquisa')], max_length=2),
        ),
    ]
