# Generated by Django 5.0.6 on 2024-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0002_pastor_alter_biblia_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palestra', models.CharField(choices=[('R', 'Reconliciação'), ('F', 'Futuro'), ('RL', 'Resilencia')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='pastor',
            name='teste',
            field=models.CharField(choices=[('N1', 'Teste Numero 1'), ('N2', 'Teste Numero 2'), ('N3', 'Teste Numero 3')], max_length=10),
        ),
    ]
