# Generated by Django 5.0.6 on 2024-06-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='exame_solicitado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
