# Generated by Django 5.0.6 on 2024-06-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='foto_perfil/')),
                ('ano_fabricacao', models.PositiveIntegerField()),
                ('acessorios', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tipo', models.CharField(choices=[('S', 'Sedan'), ('H', 'Hatch'), ('C', 'Caminhonete')], max_length=4)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ('pk',),
            },
        ),
    ]
