# Generated by Django 5.0.6 on 2024-09-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='tipo',
            field=models.CharField(choices=[('SED', 'Sedan'), ('SUV', 'SUV'), ('HAT', 'HATchback')], max_length=3),
        ),
        migrations.AlterField(
            model_name='carro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
