# Generated by Django 5.0.6 on 2024-06-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mensagem', models.CharField(max_length=30)),
                ('valor_mensagem', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
